trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - master
      - release/*
      - feature/*
      - bug/*
  paths:
    exclude:
      - README.md

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_CONTAINER_REGISTRY: 'Decentralized Cloud Docker Hub'
  DOCKER_REPOSITORY_NAME: 'decentralizedcloud/api-gateway'

steps:
- task: Bash@3
  displayName: "Generating docker tags"
  inputs:
    filePath: '$(system.defaultWorkingDirectory)/script/generate-version.sh'
    arguments: $(Build.SourceBranch)

- task: Bash@3
  displayName: "Build GraphQL contract"
  inputs:
    filePath: '$(system.defaultWorkingDirectory)/script/compile-graphql.sh'
    arguments: '$(system.defaultWorkingDirectory)/script'

- task: Docker@2
  displayName: "Build"
  inputs:
    repository: $(DOCKER_REPOSITORY_NAME)
    command: 'build'
    Dockerfile: '$(system.defaultWorkingDirectory)/docker/Dockerfile.build'
    buildContext: '$(system.defaultWorkingDirectory)'
    arguments: '--build-arg VERSION=$(VERSION)'
    tags: $(VERSION)

- task: Docker@2
  displayName: "Test and Coverage"
  inputs:
    command: 'build'
    Dockerfile: '$(system.defaultWorkingDirectory)/docker/Dockerfile.testAndCoverage'
    buildContext: '$(system.defaultWorkingDirectory)'
    arguments: '--build-arg CI_SERVICE=$(CI_SERVICE) --build-arg COVERALLS_TOKEN=$(COVERALLS_TOKEN)'

- task: Docker@2
  displayName: Docker Login
  inputs:
    containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
    command: 'login'

- task: Docker@2
  displayName: Push
  inputs:
    containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
    repository: $(DOCKER_REPOSITORY_NAME)
    command: 'push'
    buildContext: '$(system.defaultWorkingDirectory)'
    tags: $(VERSION)

- task: Docker@2
  displayName: Docker Logout
  inputs:
    containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
    command: 'logout'

