trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - master
      - release/*
      - feature/*
      - hotfix/*
  paths:
    exclude:
      - README.md
      - helm-charts/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_CONTAINER_REGISTRY: 'Decentralized Cloud Docker Hub'
  DOCKER_REPOSITORY_NAME: 'decentralizedcloud/api-gateway'

steps:
- task: GitVersion@5
  inputs:
    runtime: 'core'
    configFilePath: './GitVersion.yml'

- task: Bash@3
  displayName: "Build GraphQL contract"
  inputs:
    filePath: '$(system.defaultWorkingDirectory)/script/compile-graphql.sh'
    arguments: '$(system.defaultWorkingDirectory)/script'

- task: Docker@2
  displayName: "Build docker image"
  inputs:
    repository: $(DOCKER_REPOSITORY_NAME)
    command: 'build'
    Dockerfile: '$(system.defaultWorkingDirectory)/docker/Dockerfile.build'
    buildContext: '$(system.defaultWorkingDirectory)'
    arguments: '--build-arg VERSION=$(GitVersion.SemVer)'
    tags: $(GitVersion.SemVer)

- task: Docker@2
  displayName: "Test and Coverage"
  inputs:
    command: 'build'
    Dockerfile: '$(system.defaultWorkingDirectory)/docker/Dockerfile.testAndCoverage'
    buildContext: '$(system.defaultWorkingDirectory)'
    arguments: '--build-arg CI_SERVICE=$(CI_SERVICE) --build-arg COVERALLS_TOKEN=$(COVERALLS_TOKEN)'

- task: Docker@2
  displayName: "Docker Login"
  inputs:
    containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
    command: 'login'

- task: Docker@2
  displayName: "Push docker image"
  inputs:
    containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
    repository: $(DOCKER_REPOSITORY_NAME)
    command: 'push'
    buildContext: '$(system.defaultWorkingDirectory)'
    tags: $(GitVersion.SemVer)

- task: Docker@2
  displayName: "Docker Logout"
  inputs:
    containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
    command: 'logout'

