FROM golang:1.16
LABEL maintainer="morteza.alizadeh@gmail.com"

ARG VERSION

ADD . /src
WORKDIR /src
RUN make dep
RUN make build

FROM alpine:3
WORKDIR /
COPY --from=0 /src/bin/api-gateway .
CMD ["/api-gateway", "start"]

