// Code generated by MockGen. DO NOT EDIT.
// Source: ../contract.go

// Package mock_endpoint is a generated GoMock package.
package mock_endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockEndpointCreatorContract is a mock of EndpointCreatorContract interface
type MockEndpointCreatorContract struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointCreatorContractMockRecorder
}

// MockEndpointCreatorContractMockRecorder is the mock recorder for MockEndpointCreatorContract
type MockEndpointCreatorContractMockRecorder struct {
	mock *MockEndpointCreatorContract
}

// NewMockEndpointCreatorContract creates a new mock instance
func NewMockEndpointCreatorContract(ctrl *gomock.Controller) *MockEndpointCreatorContract {
	mock := &MockEndpointCreatorContract{ctrl: ctrl}
	mock.recorder = &MockEndpointCreatorContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEndpointCreatorContract) EXPECT() *MockEndpointCreatorContractMockRecorder {
	return m.recorder
}

// GraphQLEndpoint mocks base method
func (m *MockEndpointCreatorContract) GraphQLEndpoint() endpoint.Endpoint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GraphQLEndpoint")
	ret0, _ := ret[0].(endpoint.Endpoint)
	return ret0
}

// GraphQLEndpoint indicates an expected call of GraphQLEndpoint
func (mr *MockEndpointCreatorContractMockRecorder) GraphQLEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GraphQLEndpoint", reflect.TypeOf((*MockEndpointCreatorContract)(nil).GraphQLEndpoint))
}
